Repository ostis-dev/sc-machine, pull requests merged in 2020-11, with the labels that each got.

#329 [sc-memory] Fix typo
  sc-memory/sc-memory/python/sc_python_threads.hpp
Labels: Bug

#330 [repo] Remove unused files
  bindings/python/make.sh
  bindings/python/pysc.i
  bindings/python/pysc_types.i
  bindings/python/test.py
Labels: Refactoring

#331 [sc-memory] Replace context pointer with reference in ScSet
  docs/changelog.md
  sc-memory/sc-memory/sc_keynodes.cpp
  sc-memory/sc-memory/sc_struct.cpp
  sc-memory/sc-memory/sc_struct.hpp
  sc-memory/tests/sc-memory/common/sc-struct.cpp
  sc-memory/tests/sc-memory/templates/sc-templates-build.cpp
  sc-memory/tests/sc-memory/templates/sc-templates-common.cpp
  sc-memory/tests/sc-memory/templates/sc-templates-regression.cpp
  sc-memory/tests/sc-memory/templates/sc-templates-search.cpp
  sc-memory/tests/sc-memory/templates/sc-templates-struct.cpp
Labels: Refactoring

#338 [cmake] Set bin path to root of sc-machine(#352)
  CMakeLists.txt
  docs/changelog.md
Labels: Improvement
